name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Bluehost
        uses: easingthemes/ssh-deploy@v2.2.7
        with:
          SSH_PRIVATE_KEY: ${{ secrets.BH_SSH_KEY }}
          REMOTE_HOST: sh00069         # replace with your Bluehost server
          REMOTE_USER: fmnoevmy    # cPanel username
          REMOTE_PORT: 22                         # default SSH port
          SOURCE: public                          # local folder in your repo
          TARGET: public_html                         # remote folder on Bluehost
          EXCLUDE: ".git*"








